[project]
name = "notifications-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel del Pino", email = "gabparedes@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "sqlalchemy>=2.0.54",
]

[tool.uv]
package = false

[project.scripts]
notifications-challenge = "notifications_challenge:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
